name: fast_translation
description: Fast Translation App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  translator: ^1.0.0

flutter:
  uses-material-design:
